"""users and sessions

Revision ID: 676fc18cf7b5
Revises:
Create Date: 2026-09-21 12:29:22.100442

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "676fc18cf7b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("member", "guest", name="user_kind"), nullable=False),
        sa.Column("zitadel_sub", sa.String(length=64), nullable=True),
        sa.Column("idp_issuer", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("guest_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idp_issuer", "zitadel_sub", name="uq_users_idp_subject"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_users_guest_expires_at"), "users", ["guest_expires_at"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_users_zitadel_sub"), "users", ["zitadel_sub"], unique=False, schema="public"
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_sessions_expires_at"), "sessions", ["expires_at"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_public_sessions_user_id"), table_name="sessions", schema="public")
    op.drop_index(op.f("ix_public_sessions_expires_at"), table_name="sessions", schema="public")
    op.drop_table("sessions", schema="public")
    op.drop_index(op.f("ix_public_users_zitadel_sub"), table_name="users", schema="public")
    op.drop_index(op.f("ix_public_users_guest_expires_at"), table_name="users", schema="public")
    op.drop_table("users", schema="public")
    sa.Enum(name="user_kind").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
