"""domain tables

Revision ID: ffac2f085936
Revises: 676fc18cf7b5
Create Date: 2026-09-21 13:07:21.536898

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffac2f085936"
down_revision: str | Sequence[str] | None = "676fc18cf7b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("dedupe_key", sa.String(length=300), nullable=False),
        sa.Column("to_email", sa.String(length=320), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resend_id", sa.String(length=120), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_email_log_dedupe_key"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_email_log_user_id"), "email_log", ["user_id"], unique=False, schema="public"
    )
    op.create_table(
        "files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("thumb_key", sa.String(length=512), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=160), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(op.f("ix_public_files_owner_id"), "files", ["owner_id"], unique=False, schema="public")
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("project", "study", name="group_kind"), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("subject", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("invite_code", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_code", name="uq_groups_invite_code"),
        schema="public",
    )
    op.create_index(op.f("ix_public_groups_owner_id"), "groups", ["owner_id"], unique=False, schema="public")
    op.create_table(
        "notification_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snoozed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name="uq_notification_states_user_key"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_notification_states_user_id"),
        "notification_states",
        ["user_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_subjects_owner_id"), "subjects", ["owner_id"], unique=False, schema="public"
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "type", sa.Enum("exam", "session", "meeting", "personal", name="event_type"), nullable=False
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("reminder_minutes", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["public.groups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(op.f("ix_public_events_group_id"), "events", ["group_id"], unique=False, schema="public")
    op.create_index(op.f("ix_public_events_owner_id"), "events", ["owner_id"], unique=False, schema="public")
    op.create_index(
        op.f("ix_public_events_starts_at"), "events", ["starts_at"], unique=False, schema="public"
    )
    op.create_table(
        "group_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["public.groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_group_links_group_id"), "group_links", ["group_id"], unique=False, schema="public"
    )
    op.create_table(
        "group_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.Enum("owner", "member", name="group_role"), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["public.groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_members_group_user"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_group_members_group_id"), "group_members", ["group_id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_group_members_user_id"), "group_members", ["user_id"], unique=False, schema="public"
    )
    op.create_table(
        "group_topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["public.groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_group_topics_group_id"), "group_topics", ["group_id"], unique=False, schema="public"
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Enum("todo", "doing", "done", name="task_status"), nullable=False),
        sa.Column("priority", sa.Enum("low", "med", "high", name="task_priority"), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("(owner_id IS NULL) <> (group_id IS NULL)", name="ck_tasks_owner_xor_group"),
        sa.ForeignKeyConstraint(["created_by"], ["public.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["group_id"], ["public.groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(op.f("ix_public_tasks_due_at"), "tasks", ["due_at"], unique=False, schema="public")
    op.create_index(op.f("ix_public_tasks_group_id"), "tasks", ["group_id"], unique=False, schema="public")
    op.create_index(op.f("ix_public_tasks_owner_id"), "tasks", ["owner_id"], unique=False, schema="public")
    op.create_index(op.f("ix_public_tasks_status"), "tasks", ["status"], unique=False, schema="public")
    op.create_table(
        "notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("scope", sa.Enum("personal", "group", name="note_scope"), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("note", "handwritten", "slides", "paper", "link", "request", name="note_type"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.String(length=20000), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("request_open", sa.Boolean(), nullable=True),
        sa.Column("request_answered_by", sa.Uuid(), nullable=True),
        sa.Column("request_answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_answer_note_id", sa.Uuid(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(scope = 'personal' AND owner_id IS NOT NULL AND group_id IS NULL)"
            " OR (scope = 'group' AND group_id IS NOT NULL AND owner_id IS NULL)",
            name="ck_notes_scope_owner_group",
        ),
        sa.ForeignKeyConstraint(["created_by"], ["public.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["file_id"], ["public.files.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["group_id"], ["public.groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["request_answer_note_id"], ["public.notes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["request_answered_by"], ["public.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_id"], ["public.subjects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["topic_id"], ["public.group_topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(op.f("ix_public_notes_group_id"), "notes", ["group_id"], unique=False, schema="public")
    op.create_index(op.f("ix_public_notes_owner_id"), "notes", ["owner_id"], unique=False, schema="public")
    op.create_index(
        op.f("ix_public_notes_subject_id"), "notes", ["subject_id"], unique=False, schema="public"
    )
    op.create_index(op.f("ix_public_notes_topic_id"), "notes", ["topic_id"], unique=False, schema="public")
    op.create_table(
        "task_assignees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["public.tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "user_id", name="uq_task_assignees_task_user"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_task_assignees_task_id"), "task_assignees", ["task_id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_task_assignees_user_id"), "task_assignees", ["user_id"], unique=False, schema="public"
    )
    op.create_table(
        "task_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["public.tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_task_links_task_id"), "task_links", ["task_id"], unique=False, schema="public"
    )
    op.create_table(
        "task_subtasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["public.tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_task_subtasks_task_id"), "task_subtasks", ["task_id"], unique=False, schema="public"
    )
    # Hand-reviewed: the autogenerated drop/recreate of sessions.user_id -> users.id
    # is schema-qualified FK churn with no schema change; dropped on purpose.
    # server_default keeps the new NOT NULL columns safe on a populated table.
    op.add_column("users", sa.Column("program", sa.String(length=160), nullable=False, server_default=""))
    op.add_column("users", sa.Column("color", sa.String(length=16), nullable=False, server_default="amber"))
    op.add_column(
        "users",
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "settings")
    op.drop_column("users", "color")
    op.drop_column("users", "program")
    # Hand-reviewed: no sessions FK churn (see upgrade).
    op.drop_index(op.f("ix_public_task_subtasks_task_id"), table_name="task_subtasks", schema="public")
    op.drop_table("task_subtasks", schema="public")
    op.drop_index(op.f("ix_public_task_links_task_id"), table_name="task_links", schema="public")
    op.drop_table("task_links", schema="public")
    op.drop_index(op.f("ix_public_task_assignees_user_id"), table_name="task_assignees", schema="public")
    op.drop_index(op.f("ix_public_task_assignees_task_id"), table_name="task_assignees", schema="public")
    op.drop_table("task_assignees", schema="public")
    op.drop_index(op.f("ix_public_notes_topic_id"), table_name="notes", schema="public")
    op.drop_index(op.f("ix_public_notes_subject_id"), table_name="notes", schema="public")
    op.drop_index(op.f("ix_public_notes_owner_id"), table_name="notes", schema="public")
    op.drop_index(op.f("ix_public_notes_group_id"), table_name="notes", schema="public")
    op.drop_table("notes", schema="public")
    op.drop_index(op.f("ix_public_tasks_status"), table_name="tasks", schema="public")
    op.drop_index(op.f("ix_public_tasks_owner_id"), table_name="tasks", schema="public")
    op.drop_index(op.f("ix_public_tasks_group_id"), table_name="tasks", schema="public")
    op.drop_index(op.f("ix_public_tasks_due_at"), table_name="tasks", schema="public")
    op.drop_table("tasks", schema="public")
    op.drop_index(op.f("ix_public_group_topics_group_id"), table_name="group_topics", schema="public")
    op.drop_table("group_topics", schema="public")
    op.drop_index(op.f("ix_public_group_members_user_id"), table_name="group_members", schema="public")
    op.drop_index(op.f("ix_public_group_members_group_id"), table_name="group_members", schema="public")
    op.drop_table("group_members", schema="public")
    op.drop_index(op.f("ix_public_group_links_group_id"), table_name="group_links", schema="public")
    op.drop_table("group_links", schema="public")
    op.drop_index(op.f("ix_public_events_starts_at"), table_name="events", schema="public")
    op.drop_index(op.f("ix_public_events_owner_id"), table_name="events", schema="public")
    op.drop_index(op.f("ix_public_events_group_id"), table_name="events", schema="public")
    op.drop_table("events", schema="public")
    op.drop_index(op.f("ix_public_subjects_owner_id"), table_name="subjects", schema="public")
    op.drop_table("subjects", schema="public")
    op.drop_index(
        op.f("ix_public_notification_states_user_id"), table_name="notification_states", schema="public"
    )
    op.drop_table("notification_states", schema="public")
    op.drop_index(op.f("ix_public_groups_owner_id"), table_name="groups", schema="public")
    op.drop_table("groups", schema="public")
    op.drop_index(op.f("ix_public_files_owner_id"), table_name="files", schema="public")
    op.drop_table("files", schema="public")
    op.drop_index(op.f("ix_public_email_log_user_id"), table_name="email_log", schema="public")
    op.drop_table("email_log", schema="public")
    for enum_name in (
        "group_kind",
        "group_role",
        "task_status",
        "task_priority",
        "note_scope",
        "note_type",
        "event_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
